import { Template } from '../types';

export const DEFAULT_TEMPLATES: Template[] = [
  {
    id: 'classic-2x2',
    name: 'Classic 2x2',
    category: 'grid',
    layout: {
      type: 'grid',
      rows: 2,
      cols: 2,
      spacing: 8,
      borderRadius: 12,
      aspectRatio: '1:1',
    },
    isPremium: false,
  },
  {
    id: 'instagram-grid',
    name: 'Instagram Grid',
    category: 'social',
    layout: {
      type: 'grid',
      rows: 2,
      cols: 2,
      spacing: 4,
      borderRadius: 8,
      aspectRatio: '1:1',
    },
    isPremium: false,
  },
  {
    id: 'stories-split',
    name: 'Stories Split',
    category: 'social',
    layout: {
      type: 'grid',
      rows: 1,
      cols: 2,
      spacing: 8,
      borderRadius: 12,
      aspectRatio: '9:16',
    },
    isPremium: false,
  },
  {
    id: 'tiktok-duet',
    name: 'TikTok Duet',
    category: 'social',
    layout: {
      type: 'grid',
      rows: 1,
      cols: 2,
      spacing: 4,
      borderRadius: 8,
      aspectRatio: '9:16',
    },
    isPremium: false,
  },
  {
    id: 'classic-3x3',
    name: 'Classic 3x3',
    category: 'grid',
    layout: {
      type: 'grid',
      rows: 3,
      cols: 3,
      spacing: 8,
      borderRadius: 12,
      aspectRatio: '1:1',
    },
    isPremium: false,
  },
  {
    id: 'widescreen-split',
    name: 'Widescreen Split',
    category: 'cinematic',
    layout: {
      type: 'grid',
      rows: 1,
      cols: 2,
      spacing: 8,
      borderRadius: 12,
      aspectRatio: '16:9',
    },
    isPremium: false,
  },
  {
    id: 'triple-screen',
    name: 'Triple Screen',
    category: 'cinematic',
    layout: {
      type: 'grid',
      rows: 1,
      cols: 3,
      spacing: 8,
      borderRadius: 12,
      aspectRatio: '16:9',
    },
    isPremium: false,
  },
  {
    id: 'hexagon-grid',
    name: 'Hexagon Grid',
    category: 'creative',
    layout: {
      type: 'freeform',
      spacing: 8,
      borderRadius: 12,
      aspectRatio: '1:1',
    },
    isPremium: true,
  },
  {
    id: 'diagonal-split',
    name: 'Diagonal Split',
    category: 'creative',
    layout: {
      type: 'freeform',
      spacing: 8,
      borderRadius: 12,
      aspectRatio: '16:9',
    },
    isPremium: true,
  },
  {
    id: 'circular-spotlight',
    name: 'Circular Spotlight',
    category: 'creative',
    layout: {
      type: 'freeform',
      spacing: 8,
      borderRadius: 12,
      aspectRatio: '1:1',
    },
    isPremium: true,
  },
];
